- name: Update the system
  apt: upgrade=yes

- name: Install pip
  apt: name=python-pip

- name: Install awscli tool
  pip: name=awscli

- name: Install the ha-nat script
  copy: src=files/ha-nat.sh dest=/usr/local/bin/ha-nat.sh mode=700
